GET http://localhost:3000

###

GET http://localhost:3000/blogs

###

POST http://localhost:3000/blogs
Content-Type: application/json

{
    "title": "My blog 01",
    "content": "This is my third blog"
}

###

PUT http://localhost:3000/blogs/1
Content-Type: application/json

{
    "id": 2,
    "title": "My blog 01 - edited",
    "content": "This is my first blog"
}

###

GET http://localhost:3000/blogs/2

###

DELETE http://localhost:3000/blogs/1
